[WIP] Implement initial support for intralinks.
phaazon/cargo-sync-readme pull request #35
Opened 2020-11-25 13:36 UTC by orium

2020-12-01 10:19 UTC, orium commented
I have implemented support for standard library (`std`/`alloc`/`core`), but I think it is easier to open another PR once this one lands.

@phaazon  Can you take a look at this one when you have some time? :slightly_smiling_face:

2020-12-03 13:06 UTC, phaazon commented
Hello! Sure I will!

2020-12-05 16:24 UTC, phaazon requested changes
First pass of comments. Thanks for doing this! Btw, you seem to be parsing Rust file but is it really needed? Can’t we just use the crate name for all Markdown links looking like intra-links? What is the incentive for `syn`?

2020-12-05 16:24 UTC, phaazon commented on src/lib.rs
> +      .expect("Failed to get the name of the crate")
I’m not a huge fan of this. We should simply return `Option<&str>` and let the caller decide what to do.

2020-12-05 16:24 UTC, phaazon commented on src/main.rs
> +          });
I think the `main` function is alreadyl ong enough. Maybe you can wrap this logic in a function, or call it in `transform_readme`?

2020-12-05 16:24 UTC, phaazon commented on src/intralinks.rs
> +  mod_file.push("mod.rs");
You should be able to do that with `Path::join` instead.

2020-12-05 18:00 UTC, orium commented
> First pass of comments. Thanks for doing this! 

My pleasure.  I'll address them soon.

> Btw, you seem to be parsing Rust file but is it really needed? Can’t we just use the crate name for all Markdown links looking like intra-links? What is the incentive for `syn`?

The only reason for using `syn` is that you need to discover what type of symbol is being references (`struct`, `trait`, `fn`, `mod`, etc...), because the link contains that (e.g. https://docs.rs/archery/0.4.0/archery/shared_pointer/struct.SharedPointer.html or https://docs.rs/archery/0.4.0/archery/shared_pointer/kind/trait.SharedPointerKind.html).

I'm being careful to to explore modules that are not referenced, so we do the minimum amount of parsing necessary.  Also we don't fail the whole thing when we can't find a symbol in the code (we emit a warning).  But currently we are failing entirely if the code fails to be parsed (which I think is reasonable).

2020-12-05 19:33 UTC, orium commented
Addressed comments.

2020-12-05 19:43 UTC, phaazon commented
Yeah, seems fine. That’s a massive contribution, thanks a lot! I’ll do a second and final pass of review, especially in the intralinks module.

2020-12-08 19:56 UTC, phaazon requested changes

2020-12-08 19:56 UTC, phaazon commented on src/intralinks.rs
> +      IntraLinkError::ParseError(err) => write!(f, "NoModuleFile error: {}", err),
The error description doesn’t seem to be meaningful regarding the variant.

2020-12-08 19:56 UTC, phaazon commented on src/intralinks.rs
> +      IntraLinkError::ParseError(err) => write!(f, "NoModuleFile error: {}", err),
(I guess you copy-pasted for the `IntraLinkError::NoModuleFile` variant.

2020-12-08 19:56 UTC, phaazon commented on src/intralinks.rs
> +  file.read_to_string(&mut src)?;
You can replace all this with:

```suggestion
  let src = fs::read_to_string()?;
```

2020-12-08 19:56 UTC, phaazon commented on src/intralinks.rs
> +  file.read_to_string(&mut src)?;
(i.e. you’ll need to import `std::fs`).

2020-12-08 19:56 UTC, phaazon commented on src/intralinks.rs
> +    let str;
Not a huge fan of this variable name. It’s the same symbol as the `str` type. Plus, it doesn’t help understand what this variable is for.

2020-12-08 19:56 UTC, phaazon commented on src/intralinks.rs
> +      path: str.split("::").map(|s| s.to_owned()).collect(),
You can replace the lambda with:

```suggestion
      path: str.split("::").map(str::to_owned).collect(),
```

2020-12-08 19:56 UTC, phaazon commented on src/intralinks.rs
> +  }
I don’t like this. It means adding element will always be _O(n)_. You can switch to `&mut self` for this and let people if they want to at call site.

2020-12-08 19:56 UTC, phaazon commented on src/intralinks.rs
> +}
This function is _O(n²)_ in allocations. :eyes:. Looking at what you want to do, I think you should be able to generate your list without allocating anything by using references instead.

2020-12-08 20:21 UTC, orium commented on src/intralinks.rs
> +    let str;
it is hard to give it a meaningful name, it is slightly better now.

2020-12-08 21:32 UTC, orium commented on src/intralinks.rs
> +}
I can't think of a way except to either add a lifetime to `FQIdentifier` or to use an `Rc` and share the `Vec<_>`.  We still will need to do O(n) allocations.

2020-12-08 22:03 UTC, orium commented on src/intralinks.rs
> +}
Implemented with `Rc<_>`.  I'm not convinced this is worth the extra code complexity, particularly when taking into consideration that most symbol paths will have a relatively small depth (and we only do this for the symbols mentioned in the `//!` doc).

2020-12-09 10:41 UTC, phaazon commented on src/intralinks.rs
> +}
Hm. That seems like a complex solution but maybe I had underestimated the problem. I’ll try to look a bit more into it and I guess we can merge this.

2020-12-09 10:42 UTC, phaazon commented on src/lib.rs
> -#[derive(Debug, Eq, PartialEq)]
Can you leave `Debug` there? It’s implemented for all types in your variant.

2020-12-16 17:05 UTC, phaazon commented
Okay, sorry for the delay. I’ll have a final look tonight and merge / release it. Thanks again for your patience. :sweat_smile:

2020-12-16 17:46 UTC, phaazon commented on src/lib.rs
> +    &doc,
That reference shouldn’t be needed.

2020-12-16 19:18 UTC, orium commented
> Okay, sorry for the delay. I’ll have a final look tonight and merge / release it. Thanks again for your patience. sweat_smile

No worries.  Don't release it yet because I have support for links to stdlib ready in a branch.  I can open the PR once this lands.  It is way smaller, so it shouldn't be much easier to review than this PR :slightly_smiling_face:

2020-12-16 19:58 UTC, phaazon approved these changes
Let’s go! :) Thanks again!

2020-12-16 19:58 UTC, merged

2021-01-09 16:25 UTC, aldanor commented
Is it in plans to release a current version with this? (as it looks immensely helpful as of right now)

2021-01-09 18:50 UTC, orium commented
I have PR #38 open to also allow you to have links to the standard library.  Makes sense to include that in the release.

2021-01-12 00:04 UTC, phaazon commented
I’m currently reviewing all of the recently merged PRs. I’ll be doing a release later in the night.

2021-01-12 01:24 UTC, phaazon commented on src/intralinks.rs
> +use syn::export::{Debug, Formatter};
Goddammit I wish I saw that earlier…

2021-01-12 01:39 UTC, phaazon commented
So after a bad surprise, I have decided not to release anything until I have fixed the current situation. A regression was introduced by #35, breaking the build because of a hidden module (`serde::export`). I’ll clean up everything tomorrow.