Implement support for links to the standard library.
phaazon/cargo-sync-readme pull request #38
Opened 2020-12-16 20:05 UTC by orium

2020-12-16 20:07 UTC, orium commented
Marked as draft because I just noticed a bug.  We are detecting links inside backticked stuff, which should be skipped.  It is not a trivial fix and there will likely be other edge cases, so I might take a look at a proper markdown parser to extract the links (I'm gonna take a loo at pulldown_cmark).

2020-12-16 23:12 UTC, orium commented
`pulldown_cmark` solved the misidentified link inside code blocks and I could get rid of that ugly and complex link parser.  Ready for review :slightly_smiling_face:

2020-12-23 00:22 UTC, phaazon requested changes

2020-12-23 00:22 UTC, phaazon commented on src/intralinks.rs
> +      // If a module is gated by `#[cfg(test)]` we skip it.  This is happens sometimes in the
```suggestion
      // If a module is gated by `#[cfg(test)]` we skip it.  This happens sometimes in the
```

2021-01-12 00:05 UTC, phaazon approved these changes

2021-01-12 00:05 UTC, merged

2021-01-12 18:19 UTC, orium commented
Thanks for merging this @phaazon.  Just a small thing about the [CHANGELOG.md](https://github.com/phaazon/cargo-sync-readme/blob/master/CHANGELOG.md#11), where is

> This allows to point correctly to the right crates.io link

there should be

> This allows to point correctly to the right docs.rs link

Also, it is worth mentioning that links to the standard library will also point to the documentation in doc.rust-lang.org