Added integration tests.
phaazon/cargo-sync-readme pull request #53
Opened 2021-01-16 16:14 UTC by orium

A lot of stuff is not easy or possible to test in unit tests.  This left a few things without tests, like module traversal and standard library links replacement.

2021-01-18 11:29 UTC, phaazon requested changes
Thanks for the contribution. A bunch of things to fix, but overall a cool addition for the future stability and regression checks.

2021-01-18 11:29 UTC, phaazon commented on .github/workflows/ci.yaml
> +          rustup component add rust-src
Please add a comment explaining why this is needed. It’s due to the link resolution but please put it in the yaml.

2021-01-18 11:29 UTC, phaazon commented on .github/workflows/ci.yaml
> +          rustup component add rust-src
Ditto.

2021-01-18 11:29 UTC, phaazon commented on .github/workflows/ci.yaml
> +          rustup component add rust-src
Ditto.

2021-01-18 11:29 UTC, phaazon commented on tests/intralinks_ambiguous_module/src/main.rs
> +    struct MyStruct {}
Please respect the `rustfmt.toml` formatting.

2021-01-18 11:29 UTC, phaazon commented on tests/intralinks_module_walk/src/foo/mod.rs
> +
Remove this empty line.

2021-01-18 11:29 UTC, phaazon commented on tests/intralinks_simple/src/main.rs
> +//! This [this crate](crate) is cool because it contains [modules](crate::amodule) and some
I guess you can use `[This crate]` or `This [crate]` but the repetition looks weird.

2021-01-18 11:29 UTC, phaazon commented on tests/intralinks_simple/src/main.rs
> +//! This link is [broken](crate::broken), but this should [wor\\k \[fi\]le](f\\i\(n\)e).
file fine?

2021-01-18 11:29 UTC, phaazon commented on tests/intralinks_simple/src/main.rs
> +    }
`rustfmt` indent.

2021-01-18 11:29 UTC, phaazon commented on tests/tests.rs
> +      .expect("Binary not found")
Replace this error message with something more obvious, like `cargo-sync-readme binary not found`.

2021-01-18 11:29 UTC, phaazon commented on tests/tests.rs
> +    );
I’m not sure about all this; why not use the `-c` switch, which does the same thing without having to generate the file in the first place?

2021-01-18 21:00 UTC, orium commented on tests/tests.rs
> +    );
The point is to test that the README generation is correctly done.  If we were to use `-c` it would not be such a strong test: for instance, if `-c` erroneously didn't detect a change, or even if the program exited prematurely the tests would pass.

Checking that we actually generate the README correctly is a strong proof that the tool can generate the correct README.

2021-01-18 21:26 UTC, orium commented
Addressed comments.  Ended up simplifying the ci setup a bit.

2021-01-26 17:34 UTC, phaazon approved these changes
Just small nits and should be okay. Thanks.

2021-01-26 17:34 UTC, phaazon commented on .github/workflows/ci.yaml
> +          # to the standard library as correctly generated.
```suggestion
          # to the standard library are correctly generated.
```

2021-01-26 17:34 UTC, phaazon commented on .github/workflows/ci.yaml
> +          done
Isn’t there a way to test that directly from within the main project?

2021-01-26 20:17 UTC, orium commented on .github/workflows/ci.yaml
> +          done
This code is not part of the `cargo-sync-readme` project.  These are test cargo projects that mimic a project someone might use `cargo-sync-readme` on.

I checked if `cargo` had a flag to say "please execute like you where in directory x", but I didn't find anything.

Btw, the reason why `cargo fmt` uses the same rustfmt configuration is that if there isn't a `.rustfmt.conf` in the current directory it will search in parent directories for one.

2021-01-28 11:12 UTC, phaazon commented on .github/workflows/ci.yaml
> +          done
This code is rather complicated for what it’s doing. `pushd` and `popd` are not even required. Either use a subshell or simply use the `--manifest-path` switch.

2021-01-28 16:01 UTC, phaazon approved these changes

2021-01-28 16:01 UTC, merged